function gainXp(n){G.xp+=n;if(G.xp>=G.nextXp&&!levelPending){levelPending=true;setTimeout(function(){if(G.state==='play')levelUp()},80)}}

function updatePlayer(dt){
 var ix=input.x+(input.keys.KeyD||input.keys.ArrowRight?1:0)-(input.keys.KeyA||input.keys.ArrowLeft?1:0),iy=input.y+(input.keys.KeyS||input.keys.ArrowDown?1:0)-(input.keys.KeyW||input.keys.ArrowUp?1:0),m=len(ix,iy);if(m>1){ix/=m;iy/=m}
 var acc=P.speed*(P.dashTime>0?2.6:1);P.vx+=ix*acc*dt*7;P.vy+=iy*acc*dt*7;var drag=Math.pow(P.dashTime>0?.22:.006,dt);P.vx*=drag;P.vy*=drag;P.x+=P.vx*dt;P.y+=P.vy*dt;if(m>.1)P.angle=Math.atan2(iy,ix);P.dashReady=Math.max(0,P.dashReady-dt);P.dashTime=Math.max(0,P.dashTime-dt);P.inv=Math.max(0,P.inv-dt);P.fireCd-=dt;if(P.fireCd<=0)fire();if(P.regen)P.hp=Math.min(P.maxHp,P.hp+P.regen*dt);
 P.trail.unshift({x:P.x,y:P.y,life:1});if(P.trail.length>16)P.trail.pop();
}
function updateEnemies(dt){
 var slow=G.slow>0?.34:1;for(var i=0;i<enemies.length;i++){var e=enemies[i];if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.contact=Math.max(0,e.contact-dt);var dx=P.x-e.x,dy=P.y-e.y,d=len(dx,dy)||1;
 if(e.type==='drift'||e.type==='split'||e.type==='mite'){e.vx+=(dx/d*e.speed-e.vx)*dt*2.3*slow;e.vy+=(dy/d*e.speed-e.vy)*dt*2.3*slow}
 if(e.type==='blade'){e.cool-=dt*slow;if(e.state===0){e.vx+=(dx/d*.55-e.vx)*dt*2;e.vy+=(dy/d*.55-e.vy)*dt*2;if(e.cool<=0&&d<8){e.state=1;e.cool=.7;e.angle=Math.atan2(dy,dx);ring(e.x,e.y,'#e7b960',.2,1.2,.5)}}else if(e.state===1){e.vx*=.82;e.vy*=.82;if((e.cool-=dt)<=0){e.state=2;e.cool=.55;e.vx=Math.cos(e.angle)*9;e.vy=Math.sin(e.angle)*9;tone(150,.12,'sawtooth',.03,160)}}else{if((e.cool-=dt)<=0){e.state=0;e.cool=rnd(2.4,1.5)}}}
 if(e.type==='seer'){e.cool-=dt*slow;var desired=d<5?-1:d>7?1:0;e.vx+=(dx/d*e.speed*desired-e.vx)*dt*1.5;e.vy+=(dy/d*e.speed*desired-e.vy)*dt*1.5;if(e.cool<=0){e.cool=rnd(2,1.4);var a=Math.atan2(dy,dx);enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(a)*4.2,vy:Math.sin(a)*4.2,r:.15,life:4,damage:11,color:'#7cc9c3'});tone(210,.12,'sine',.025,-60)}}
 if(e.type==='boss')updateBoss(e,dt,dx,dy,d,slow);
 e.x+=e.vx*dt*slow;e.y+=e.vy*dt*slow;e.vx*=Math.pow(.55,dt);e.vy*=Math.pow(.55,dt);if(d<P.r+e.r&&e.contact<=0){hurt(e.damage,e.x,e.y);e.contact=.8}
 }
 enemies=enemies.filter(function(e){return !e.dead||e.type==='boss'&&e.hit>0});
}
function updateBoss(e,dt,dx,dy,d,slow){e.cool-=dt*slow;if(e.hp<e.max*.62&&!e.phase2){e.phase2=true;msg('PHASE II','CURATORが庭園を折り畳む',1200);for(var i=0;i<5;i++)spawn('blade',e.x+rnd(3,-3),e.y+rnd(3,-3));G.flash=.5}if(e.hp<e.max*.28&&!e.phase3){e.phase3=true;msg('FINAL CUT','逃げ場が消える',1200);for(i=0;i<5;i++)spawn('seer',e.x+rnd(4,-4),e.y+rnd(4,-4));G.flash=.5}
 var sp=e.phase3?1.2:e.phase2?.95:.72;e.vx+=(dx/d*sp-e.vx)*dt*.8;e.vy+=(dy/d*sp-e.vy)*dt*.8;
 if(e.cool<=0){var mode=Math.random();if(mode<.45){var count=e.phase3?22:e.phase2?16:12;for(i=0;i<count;i++){var a=i/count*TAU+G.time*.2;enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(a)*(e.phase3?5:3.8),vy:Math.sin(a)*(e.phase3?5:3.8),r:.16,life:5,damage:12,color:'#e7b960'})}ring(e.x,e.y,'#e7b960',.4,3,.5);e.cool=e.phase3?1.2:1.8}else if(mode<.76){a=Math.atan2(dy,dx);for(i=-2;i<=2;i++)enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(a+i*.13)*6,vy:Math.sin(a+i*.13)*6,r:.17,life:4,damage:15,color:'#eee4cc'});e.cool=1.35}else{for(i=0;i<(e.phase2?4:2);i++)spawn(Math.random()<.5?'drift':'blade',e.x+rnd(3,-3),e.y+rnd(3,-3));e.cool=2.3}tone(75,.18,'square',.035,30)}}
function updateBullets(dt){
 for(var i=bullets.length-1;i>=0;i--){var b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;var remove=b.life<=0;for(var j=0;j<enemies.length&&!remove;j++){var e=enemies[j];if(e.dead)continue;var dx=e.x-b.x,dy=e.y-b.y,rr=e.r+b.r;if(dx*dx+dy*dy<rr*rr){damageEnemy(e,b.damage,false);burst(b.x,b.y,b.color,4,2);if(b.bounces>0){var target=null,bd=25;for(var k=0;k<enemies.length;k++){var o=enemies[k];if(o===e||o.dead)continue;var dd=(o.x-e.x)*(o.x-e.x)+(o.y-e.y)*(o.y-e.y);if(dd<bd){bd=dd;target=o}}if(target){var a=Math.atan2(target.y-e.y,target.x-e.x);b.x=e.x;b.y=e.y;b.vx=Math.cos(a)*P.bulletSpeed;b.vy=Math.sin(a)*P.bulletSpeed;b.bounces--;continue}}if(b.pierce>0)b.pierce--;else remove=true}}
 if(remove)bullets.splice(i,1)}
 for(i=enemyBullets.length-1;i>=0;i--){b=enemyBullets[i];b.x+=b.vx*dt*(G.slow>0?.45:1);b.y+=b.vy*dt*(G.slow>0?.45:1);b.life-=dt;dx=P.x-b.x;dy=P.y-b.y;if(dx*dx+dy*dy<(P.r+b.r)*(P.r+b.r)){hurt(b.damage,b.x,b.y);b.life=0}if(b.life<=0)enemyBullets.splice(i,1)}
}
function updateOrbiters(dt){if(!P.orbiters)return;for(var i=0;i<P.orbiters;i++){var a=G.time*2.4+i/P.orbiters*TAU,ox=P.x+Math.cos(a)*1.25,oy=P.y+Math.sin(a)*1.25;for(var j=0;j<enemies.length;j++){var e=enemies[j];if(e.dead)continue;var dx=e.x-ox,dy=e.y-oy;if(dx*dx+dy*dy<(e.r+.22)*(e.r+.22)&&(!e.orbitHit||G.time-e.orbitHit>.38)){e.orbitHit=G.time;damageEnemy(e,P.orbitalDamage,false)}}}}
function updateDrops(dt){for(var i=drops.length-1;i>=0;i--){var d=drops[i],dx=P.x-d.x,dy=P.y-d.y,dd=len(dx,dy)||1;if(dd<P.magnet){var f=(1-dd/P.magnet)*24+4;d.vx+=dx/dd*f*dt;d.vy+=dy/dd*f*dt}d.x+=d.vx*dt;d.y+=d.vy*dt;d.vx*=Math.pow(.08,dt);d.vy*=Math.pow(.08,dt);d.life-=dt;if(dd<.55){gainXp(1);tone(660,.05,'sine',.018,80);drops.splice(i,1)}else if(d.life<=0)drops.splice(i,1)}}
function updateFx(dt){G.shake=Math.max(0,G.shake-dt*1.8);G.flash=Math.max(0,G.flash-dt*2);G.slow=Math.max(0,G.slow-dt);for(var i=particles.length-1;i>=0;i--){var p=particles[i];p.life-=dt;p.vz-=6*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vx*=p.drag;p.vy*=p.drag;if(p.life<=0)particles.splice(i,1)}for(i=rings.length-1;i>=0;i--){var r=rings[i];r.life-=dt;r.r=lerp(r.r,r.to,1-Math.pow(.002,dt));if(r.life<=0)rings.splice(i,1)}for(i=texts.length-1;i>=0;i--){var t=texts[i];t.life-=dt;t.z+=dt*.85;if(t.life<=0)texts.splice(i,1)}}
function update(dt){if(G.state!=='play')return;G.time+=dt;G.runTime+=dt;spawnDirector(dt);if(G.runTime>=60&&!G.bossSpawned)spawnBoss();updatePlayer(dt);updateEnemies(dt);updateBullets(dt);updateOrbiters(dt);updateDrops(dt);updateFx(dt);G.score+=dt*(10+G.level*1.3);updateUI()}

function finish(win){if(G.state==='end')return;G.state='end';ui.end.classList.remove('hidden');G.best=Math.max(G.best,Math.floor(G.score));try{localStorage.setItem('vantaBloomBest',G.best)}catch(e){}ui.endEye.textContent=win?'THE GARDEN COULD NOT CONTAIN YOU':'THE CURATOR CLOSES THE ARCHIVE';ui.endTitle.textContent=win?'BLOOMED':'PRUNED';ui.endText.textContent=win?'あなたは庭園の作品ではなく、庭園を書き換える生命になった。':'陶器の身体は砕けた。それでも次の種は、同じ失敗を記憶している。';ui.endScore.textContent=Math.floor(G.score);ui.endKills.textContent=G.kills;ui.endLevel.textContent=G.level;ui.bestText.textContent='BEST '+G.best;releasePointer({pointerId:input.id});tone(win?180:60,.9,win?'sine':'sawtooth',.09,win?650:-20)}
