var cam={x:0,y:0};
function project(x,y,z){return{x:W*.5+(x-cam.x)*S,y:H*.47+(y-cam.y)*S*.66-(z||0)*S,s:S}}
function colorScale(hex,k){var n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return'rgb('+(clamp(r*k,0,255)|0)+','+(clamp(g*k,0,255)|0)+','+(clamp(b*k,0,255)|0)+')'}
function poly(points,fill,alpha){ctx.globalAlpha=alpha===undefined?1:alpha;ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(var i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();ctx.fill()}
function prism(x,y,r,h,sides,rot,color,alpha){var base=project(x,y,0),top=project(x,y,h),ptsB=[],ptsT=[];for(var i=0;i<sides;i++){var a=rot+i/sides*TAU;ptsB.push([base.x+Math.cos(a)*r*S,base.y+Math.sin(a)*r*S*.42]);ptsT.push([top.x+Math.cos(a)*r*S,top.y+Math.sin(a)*r*S*.42])}for(i=0;i<sides;i++){var n=(i+1)%sides,k=.56+.24*(i/sides);poly([ptsB[i],ptsB[n],ptsT[n],ptsT[i]],colorScale(color,k),alpha)}poly(ptsT,colorScale(color,1.05),alpha)}
function diamond(x,y,r,h,color,rot,alpha){prism(x,y,r,h,4,rot,color,alpha)}
function shadow(x,y,r,a){var p=project(x,y,0);ctx.globalAlpha=a||.25;ctx.fillStyle='#05070a';ctx.beginPath();ctx.ellipse(p.x,p.y,r*S,r*S*.28,0,0,TAU);ctx.fill()}
function circleWorld(x,y,r,color,alpha,z){var p=project(x,y,z||0);ctx.globalAlpha=alpha===undefined?1:alpha;ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,r*S,0,TAU);ctx.fill()}
function drawGround(){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#252b35');g.addColorStop(.34,'#171c23');g.addColorStop(1,'#0c1015');ctx.globalAlpha=1;ctx.fillStyle=g;ctx.fillRect(0,0,W,H);var horizon=H*.27;ctx.fillStyle='#222823';ctx.fillRect(0,horizon,W,H-horizon);ctx.save();ctx.beginPath();ctx.rect(0,horizon,W,H-horizon);ctx.clip();ctx.strokeStyle='rgba(220,225,216,.055)';ctx.lineWidth=1;var grid=2,fromX=Math.floor((cam.x-W/S/2)/grid)*grid,toX=cam.x+W/S/2+grid,fromY=Math.floor((cam.y-H/S)/grid)*grid,toY=cam.y+H/S+grid;for(var x=fromX;x<toX;x+=grid){var p1=project(x,fromY,0),p2=project(x,toY,0);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}for(var y=fromY;y<toY;y+=grid){p1=project(fromX,y,0);p2=project(toX,y,0);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}ctx.restore();var aura=ctx.createRadialGradient(W*.5,H*.46,0,W*.5,H*.46,Math.max(W,H)*.7);aura.addColorStop(0,'rgba(103,145,142,.055)');aura.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=aura;ctx.fillRect(0,0,W,H)}
function drawDecor(d){var p=project(d.x,d.y,0);if(p.x<-80||p.x>W+80||p.y<-100||p.y>H+100)return;if(d.type===0){shadow(d.x,d.y,d.s*.35,.17);prism(d.x,d.y,d.s*.28,d.s*1.8,5,d.rot,'#31383b',1)}else{shadow(d.x,d.y,d.s*.45,.14);diamond(d.x,d.y,d.s*.3,d.s*.55,'#49504c',d.rot,1)}}
function drawEnemy(e){var blink=e.hit>0&&Math.floor(G.time*28)%2===0,alpha=blink?.45:1;shadow(e.x,e.y,e.r*.95,.28);if(e.type==='blade')diamond(e.x,e.y,e.r,e.r*1.35,e.color,e.angle+Math.PI/4,alpha);else if(e.type==='seer'){prism(e.x,e.y,e.r,e.r*1.1,6,G.time*.25+e.phase,e.color,alpha);circleWorld(e.x,e.y,.12,'#d8f3ee',1,e.r*1.25)}else if(e.type==='boss'){prism(e.x,e.y,e.r,e.r*1.8,10,G.time*.1,e.color,alpha);for(var k=0;k<3;k++){var a=G.time*(.45+k*.08)+k*TAU/3,ox=e.x+Math.cos(a)*2.1,oy=e.y+Math.sin(a)*2.1;diamond(ox,oy,.28,.65,k===0?'#e7b960':k===1?'#7cc9c3':'#db6b63',-a,1)}var p=project(e.x,e.y,e.r*2.2);ctx.globalAlpha=1;ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(p.x-70,p.y-18,140,6);ctx.fillStyle='#e7b960';ctx.fillRect(p.x-70,p.y-18,140*clamp(e.hp/e.max,0,1),6)}else prism(e.x,e.y,e.r,e.r*(e.type==='split'?1.3:1),e.type==='split'?7:6,G.time*.25+e.phase,e.color,alpha)}
function render(){
 cam.x=lerp(cam.x,P?P.x:0,.09);cam.y=lerp(cam.y,P?P.y:0,.09);var sx=(Math.random()-.5)*G.shake*S*.25,sy=(Math.random()-.5)*G.shake*S*.2;cam.x-=sx/S;cam.y-=sy/(S*.66);drawGround();
 var list=[];for(var i=0;i<decor.length;i++)list.push({y:decor[i].y,kind:0,o:decor[i]});for(i=0;i<drops.length;i++)list.push({y:drops[i].y,kind:1,o:drops[i]});for(i=0;i<enemies.length;i++)if(!enemies[i].dead)list.push({y:enemies[i].y,kind:2,o:enemies[i]});if(P)list.push({y:P.y,kind:3,o:P});list.sort(function(a,b){return a.y-b.y});
 for(i=0;i<P.trail.length;i+=2){var tr=P.trail[i];shadow(tr.x,tr.y,.35,(1-i/P.trail.length)*.075)}
 for(i=0;i<list.length;i++){var it=list[i];if(it.kind===0)drawDecor(it.o);else if(it.kind===1){var d=it.o;diamond(d.x,d.y,.11,.3,'#7cc9c3',G.time*1.4,1)}else if(it.kind===2)drawEnemy(it.o);else{shadow(P.x,P.y,P.r,.32);var blink=P.inv>0&&Math.floor(G.time*16)%2===0;if(!blink){prism(P.x,P.y,P.r,.72,8,P.angle+.2,'#e9e4da',1);var eye=project(P.x+Math.cos(P.angle)*.28,P.y+Math.sin(P.angle)*.28,.5);ctx.fillStyle='#7cc9c3';ctx.globalAlpha=1;ctx.beginPath();ctx.arc(eye.x,eye.y,.08*S,0,TAU);ctx.fill()}if(P.shield>0){var pp=project(P.x,P.y,.45);ctx.strokeStyle='rgba(124,201,195,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pp.x,pp.y,.75*S,0,TAU);ctx.stroke()}}}
 if(P&&P.orbiters){for(i=0;i<P.orbiters;i++){var a=G.time*2.4+i/P.orbiters*TAU;diamond(P.x+Math.cos(a)*1.25,P.y+Math.sin(a)*1.25,.16,.42,'#e7b960',-a,1)}}
 for(i=0;i<bullets.length;i++){var b=bullets[i];circleWorld(b.x,b.y,b.r,b.color,1,.25)}for(i=0;i<enemyBullets.length;i++){b=enemyBullets[i];circleWorld(b.x,b.y,b.r,b.color,1,.25)}
 for(i=0;i<rings.length;i++){var r=rings[i],rp=project(r.x,r.y,.05);ctx.globalAlpha=clamp(r.life/r.max,0,1);ctx.strokeStyle=r.color;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(rp.x,rp.y,r.r*S,r.r*S*.42,0,0,TAU);ctx.stroke()}
 for(i=0;i<particles.length;i++){var q=particles[i],qp=project(q.x,q.y,Math.max(0,q.z));ctx.globalAlpha=clamp(q.life/q.max,0,1);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(qp.x,qp.y,Math.max(1,q.size*S),0,TAU);ctx.fill()}
 for(i=0;i<texts.length;i++){var tx=texts[i],tp=project(tx.x,tx.y,tx.z);ctx.globalAlpha=clamp(tx.life/tx.max,0,1);ctx.fillStyle=tx.color;ctx.font='900 '+tx.size+'px system-ui';ctx.textAlign='center';ctx.fillText(tx.text,tp.x,tp.y)}
 ctx.globalAlpha=1;if(P&&P.charge>0){var cp=project(P.x,P.y,.02);ctx.strokeStyle='rgba(231,185,96,'+(.12+.3*P.charge/100)+')';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(cp.x,cp.y,(.7+P.charge/180)*S,(.7+P.charge/180)*S*.4,0,0,TAU);ctx.stroke()}
 if(G.flash>0){ctx.fillStyle='rgba(240,236,226,'+(G.flash*.16)+')';ctx.fillRect(0,0,W,H)}
 var v=ctx.createRadialGradient(W*.5,H*.48,Math.min(W,H)*.18,W*.5,H*.48,Math.max(W,H)*.75);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.54)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)
}

var last=performance.now();function loop(now){var dt=Math.min(.033,(now-last)/1000);last=now;if(G.state!=='pause'&&G.state!=='upgrade'&&G.state!=='menu'&&G.state!=='end')update(dt);else if(G.state==='menu'){G.time+=dt;updateFx(dt)}render();requestAnimationFrame(loop)}
reset();G.state='menu';requestAnimationFrame(loop);
